// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrideWeddingPlanners.Models;

namespace PrideWeddingPlanners.Migrations
{
    [DbContext(typeof(WeddingDBContext))]
    [Migration("20210115093842_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("PrideWeddingPlanners.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("customer_no")
                        .HasColumnType("int");

                    b.Property<string>("vendor_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AdminTable");
                });

            modelBuilder.Entity("PrideWeddingPlanners.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("L_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("client_NIC")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tele_no")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ClientTable");
                });

            modelBuilder.Entity("PrideWeddingPlanners.Models.Client_Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ClientAccountTable");
                });

            modelBuilder.Entity("PrideWeddingPlanners.Models.Packages", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("eackage_no")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("end_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("start_date")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PackagesTable");
                });

            modelBuilder.Entity("PrideWeddingPlanners.Models.Payments", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("card_no")
                        .HasColumnType("int");

                    b.Property<string>("cardholder_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cvc")
                        .HasColumnType("int");

                    b.Property<int>("exp_date")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PaymentsTable");
                });

            modelBuilder.Entity("PrideWeddingPlanners.Models.Vendor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("company_catogary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tele_no")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("VendorTable");
                });

            modelBuilder.Entity("PrideWeddingPlanners.Models.Vendor_Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("password")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("VendorAccountTable");
                });
#pragma warning restore 612, 618
        }
    }
}
